# This is a basic workflow to help you get started with Actions

name: Liquibase_mariadb_GitHub-Hosted

# Controls when the action will run. 
on:

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      mariadb_dev:
        # Docker Hub image
        image: mariadb:latest
        # Provide the password for mariadb
        env:
          MARIADB_ROOT_PASSWORD: mariadb
          MARIADB_DATABASE: mariadb_dev
        ports:
          - 3306:3306
        # Set health checks to wait until mariadb has started
        options: >-
          --health-cmd `mysqladmin -uroot -p$MARIADB_ROOT_PASSWORD ping -h localhost`
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      mariadb_test:
        # Docker Hub image
        image: mariadb:latest
        # Provide the password for mariadb
        env:
          MARIADB_ROOT_PASSWORD: mariadb
          MARIADB_DATABASE: mariadb_test
        ports:
          - 3307:3306
        # Set health checks to wait until mariadb has started
        options: >-
          --health-cmd `mysqladmin -uroot -p$MARIADB_ROOT_PASSWORD ping -h localhost`
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run Liquibase Commands
        run: |
          curl -L https://github.com/liquibase/liquibase/releases/download/v4.15.0/liquibase-4.15.0.zip --output liquibase-4.15.0.zip
          unzip -o -d liquibase liquibase-4.15.0.zip
          ./liquibase/liquibase --version
          ./liquibase/liquibase --changeLogFile=./changelog.mariadb.sql --url=jdbc:mariadb://127.0.0.1:5432/mariadb_dev --username=root --password=mariadb status --verbose
          ./liquibase/liquibase --changeLogFile=./changelog.mariadb.sql --url=jdbc:mariadb://127.0.0.1:5432/mariadb_dev checks show
          ./liquibase/liquibase --changeLogFile=./changelog.mariadb.sql --url=jdbc:mariadb://127.0.0.1:5432/mariadb_dev checks run
          ./liquibase/liquibase --changeLogFile=./changelog.mariadb.sql --url=jdbc:mariadb://127.0.0.1:5432/mariadb_dev --username=root --password=mariadb updateSQL
          ./liquibase/liquibase --changeLogFile=./changelog.mariadb.sql --url=jdbc:mariadb://127.0.0.1:5432/mariadb_dev --username=root --password=mariadb tag version1
          ./liquibase/liquibase --changeLogFile=./changelog.mariadb.sql --url=jdbc:mariadb://127.0.0.1:5432/mariadb_dev --logLevel=FINE --username=root --password=mariadb update
          ./liquibase/liquibase --changeLogFile=./changelog.mariadb.sql --url=jdbc:mariadb://127.0.0.1:5432/mariadb_dev --username=root --password=mariadb rollback version1
          ./liquibase/liquibase --changeLogFile=./changelog.mariadb.sql --url=jdbc:mariadb://127.0.0.1:5433/mariadb_test --username=root --password=mariadb status --verbose

          
